include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    type_annotate_public_apis: true
    lines_longer_than_80_chars: true
    always_declare_return_types: true
    camel_case_types: true
    avoid_relative_lib_imports: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    empty_constructor_bodies: true
    always_require_non_null_named_parameters: true
    avoid_empty_else: true
    avoid_print: true
    avoid_return_types_on_setters: true
    avoid_unused_constructor_parameters: true
    prefer_single_quotes: true
    unnecessary_new: true
    unnecessary_parenthesis: true
    always_put_required_named_parameters_first: true
    avoid_init_to_null: true
    empty_catches: true
    unnecessary_brace_in_string_interps: true
    avoid_types_as_parameter_names: true
    prefer_final_locals: true
    file_names: true
    avoid_positional_boolean_parameters: true
    unnecessary_const: true
    unnecessary_overrides: true
    prefer_const_constructors:true: true
    prefer_const_declarations: true
