name: daily_phrases
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  share_plus: ^2.1.4
  screenshot: ^1.2.3
  path_provider: ^2.0.2
  snack: ^2.0.0
  google_fonts: ^2.1.0
  flutter_translate: ^3.0.1
  shared_preferences: ^2.0.6
  provider: ^5.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  effective_dart: ^1.3.2
  mocktail: ^0.0.1-dev.11
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/Icon-192.png
    - assets/Icon-512.png
    - assets/favicon.png
