name: daily-phrases
version: "1.0.0+2"
summary: Get phrases to share on your social networks
description: Get phrases to share on your social networks and your friends

confinement: strict
base: core18

parts:
  daily-phrases:
    plugin: flutter
    source: https://github.com/wendreof/daily_phrases.git
    flutter-target: lib/main.dart

apps:
  daily-phrases:
    command: daily_phrases
    extensions: [flutter-dev]
