name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: "12.x"
  FLUTTER_VERSION: "2.2.3"
  FLUTTER_CHANNEL: "stable"

jobs:
  flutter_test:
    name: Analyze & format & testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: |
          flutter clean
          flutter pub get
          flutter analyze
          flutter format --dry-run --set-exit-if-changed lib/
          flutter format --dry-run --set-exit-if-changed test/
          flutter test --coverage
          flutter test --machine > test-results.json
      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 0
